//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService
{
    using System;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public sealed partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Id = Guid.NewGuid();
        }

        public Client(Guid id)
        {
            this.Id = id;
        }

        [OnDeserializing]
        private void SetValuesOnDeserializing(StreamingContext context)
        {
            this.Id = Guid.NewGuid();
        }

        [DataMember]
        public System.Guid Id { get; set; }

        [DataMember]
        public string Nume { get; set; }

        [DataMember]
        public string Prenume { get; set; }

        [DataMember]
        public string Adresa { get; set; }

        [DataMember]
        public string Localitate { get; set; }

        [DataMember]
        public string Judet { get; set; }

        [DataMember]
        public string Telefon { get; set; }

        [DataMember]
        public string Email { get; set; }
    }
}
