//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService
{
    using System;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Comanda
    {
        public Comanda()
        {
            this.Id = Guid.NewGuid();
        }

        public Comanda(Guid id)
        {
            this.Id = id;
        }
        public System.Guid Id { get; set; }

        [DataMember]
        public StareComanda StareComanda { get; set; }

        [DataMember]
        public System.DateTime DataSystem { get; set; }

        [DataMember]
        public System.DateTime DataProgramare { get; set; }

        [DataMember]
        public Nullable<System.DateTime> DataFinalizare { get; set; }

        [DataMember]
        public Nullable<int> KmBoard { get; set; }

        [DataMember]
        public string Descriere { get; set; }

        [DataMember]
        public Nullable<decimal> ValoarePiese { get; set; }

        [DataMember]
        public virtual Client Client { get; set; }

        [DataMember]
        public virtual Auto Auto { get; set; }
    }
}
