//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService
{
    using System;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public sealed partial class Mecanic
    {
        public Mecanic()
        {
            this.Id = Guid.NewGuid();
        }

        [DataMember]
        public System.Guid Id { get; set; }

        [DataMember]
        public string Nume { get; set; }

        [DataMember]
        public string Prenume { get; set; }
    }
}
