//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AdresaField;
        
        private string EmailField;
        
        private System.Guid IdField;
        
        private string JudetField;
        
        private string LocalitateField;
        
        private string NumeField;
        
        private string PrenumeField;
        
        private string TelefonField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresa
        {
            get
            {
                return this.AdresaField;
            }
            set
            {
                this.AdresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Judet
        {
            get
            {
                return this.JudetField;
            }
            set
            {
                this.JudetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localitate
        {
            get
            {
                return this.LocalitateField;
            }
            set
            {
                this.LocalitateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume
        {
            get
            {
                return this.NumeField;
            }
            set
            {
                this.NumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume
        {
            get
            {
                return this.PrenumeField;
            }
            set
            {
                this.PrenumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon
        {
            get
            {
                return this.TelefonField;
            }
            set
            {
                this.TelefonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auto", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    public partial class Auto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CarService.Client ClientField;
        
        private System.Guid IdField;
        
        private string NumarAutoField;
        
        private CarService.Sasiu SasiuField;
        
        private string SerieSasiuField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Client Client
        {
            get
            {
                return this.ClientField;
            }
            set
            {
                this.ClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumarAuto
        {
            get
            {
                return this.NumarAutoField;
            }
            set
            {
                this.NumarAutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Sasiu Sasiu
        {
            get
            {
                return this.SasiuField;
            }
            set
            {
                this.SasiuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerieSasiu
        {
            get
            {
                return this.SerieSasiuField;
            }
            set
            {
                this.SerieSasiuField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sasiu", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    public partial class Sasiu : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodSasiuField;
        
        private string DenumireField;
        
        private System.Guid IdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodSasiu
        {
            get
            {
                return this.CodSasiuField;
            }
            set
            {
                this.CodSasiuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire
        {
            get
            {
                return this.DenumireField;
            }
            set
            {
                this.DenumireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Material", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    public partial class Material : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal CantitateField;
        
        private System.DateTime DataAprovizionareField;
        
        private string DenumireField;
        
        private System.Guid IdField;
        
        private decimal PretField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cantitate
        {
            get
            {
                return this.CantitateField;
            }
            set
            {
                this.CantitateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataAprovizionare
        {
            get
            {
                return this.DataAprovizionareField;
            }
            set
            {
                this.DataAprovizionareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire
        {
            get
            {
                return this.DenumireField;
            }
            set
            {
                this.DenumireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Pret
        {
            get
            {
                return this.PretField;
            }
            set
            {
                this.PretField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetaliuComanda", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    public partial class DetaliuComanda : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CarService.Comanda ComandaField;
        
        private System.Guid IdField;
        
        private System.Collections.Generic.ICollection<CarService.Imagine> ImaginesField;
        
        private System.Collections.Generic.ICollection<CarService.Material> MaterialsField;
        
        private System.Collections.Generic.ICollection<CarService.Mecanic> MecaniciField;
        
        private System.Collections.Generic.ICollection<CarService.Operatie> OperatiesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Comanda Comanda
        {
            get
            {
                return this.ComandaField;
            }
            set
            {
                this.ComandaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.ICollection<CarService.Imagine> Imagines
        {
            get
            {
                return this.ImaginesField;
            }
            set
            {
                this.ImaginesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.ICollection<CarService.Material> Materials
        {
            get
            {
                return this.MaterialsField;
            }
            set
            {
                this.MaterialsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.ICollection<CarService.Mecanic> Mecanici
        {
            get
            {
                return this.MecaniciField;
            }
            set
            {
                this.MecaniciField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.ICollection<CarService.Operatie> Operaties
        {
            get
            {
                return this.OperatiesField;
            }
            set
            {
                this.OperatiesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comanda", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    public partial class Comanda : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CarService.Auto AutoField;
        
        private CarService.Client ClientField;
        
        private System.Nullable<System.DateTime> DataFinalizareField;
        
        private System.DateTime DataProgramareField;
        
        private System.DateTime DataSystemField;
        
        private string DescriereField;
        
        private System.Guid IdField;
        
        private System.Nullable<int> KmBoardField;
        
        private CarService.StareComanda StareComandaField;
        
        private System.Nullable<decimal> ValoarePieseField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Auto Auto
        {
            get
            {
                return this.AutoField;
            }
            set
            {
                this.AutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Client Client
        {
            get
            {
                return this.ClientField;
            }
            set
            {
                this.ClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataFinalizare
        {
            get
            {
                return this.DataFinalizareField;
            }
            set
            {
                this.DataFinalizareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataProgramare
        {
            get
            {
                return this.DataProgramareField;
            }
            set
            {
                this.DataProgramareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataSystem
        {
            get
            {
                return this.DataSystemField;
            }
            set
            {
                this.DataSystemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere
        {
            get
            {
                return this.DescriereField;
            }
            set
            {
                this.DescriereField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> KmBoard
        {
            get
            {
                return this.KmBoardField;
            }
            set
            {
                this.KmBoardField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.StareComanda StareComanda
        {
            get
            {
                return this.StareComandaField;
            }
            set
            {
                this.StareComandaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ValoarePiese
        {
            get
            {
                return this.ValoarePieseField;
            }
            set
            {
                this.ValoarePieseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Imagine", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    public partial class Imagine : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DataField;
        
        private string DescriereField;
        
        private CarService.DetaliuComanda DetaliuComandaField;
        
        private byte[] FotoField;
        
        private System.Guid IdField;
        
        private string TitluField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere
        {
            get
            {
                return this.DescriereField;
            }
            set
            {
                this.DescriereField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.DetaliuComanda DetaliuComanda
        {
            get
            {
                return this.DetaliuComandaField;
            }
            set
            {
                this.DetaliuComandaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto
        {
            get
            {
                return this.FotoField;
            }
            set
            {
                this.FotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titlu
        {
            get
            {
                return this.TitluField;
            }
            set
            {
                this.TitluField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mecanic", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    public partial class Mecanic : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        private string NumeField;
        
        private string PrenumeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume
        {
            get
            {
                return this.NumeField;
            }
            set
            {
                this.NumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume
        {
            get
            {
                return this.PrenumeField;
            }
            set
            {
                this.PrenumeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operatie", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    public partial class Operatie : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DenumireField;
        
        private System.Guid IdField;
        
        private System.Nullable<decimal> TimpExecutieField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire
        {
            get
            {
                return this.DenumireField;
            }
            set
            {
                this.DenumireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TimpExecutie
        {
            get
            {
                return this.TimpExecutieField;
            }
            set
            {
                this.TimpExecutieField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StareComanda", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    public enum StareComanda : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InAsteptare = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Executata = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Refuzata = 3,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IAutoService")]
public interface IAutoService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/CreateClient", ReplyAction="http://tempuri.org/IAutoService/CreateClientResponse")]
    bool CreateClient(CarService.Client client);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/CreateClient", ReplyAction="http://tempuri.org/IAutoService/CreateClientResponse")]
    System.Threading.Tasks.Task<bool> CreateClientAsync(CarService.Client client);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/CreateAuto", ReplyAction="http://tempuri.org/IAutoService/CreateAutoResponse")]
    bool CreateAuto(CarService.Auto auto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/CreateAuto", ReplyAction="http://tempuri.org/IAutoService/CreateAutoResponse")]
    System.Threading.Tasks.Task<bool> CreateAutoAsync(CarService.Auto auto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/CreateMaterial", ReplyAction="http://tempuri.org/IAutoService/CreateMaterialResponse")]
    bool CreateMaterial(CarService.Material material);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/CreateMaterial", ReplyAction="http://tempuri.org/IAutoService/CreateMaterialResponse")]
    System.Threading.Tasks.Task<bool> CreateMaterialAsync(CarService.Material material);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/CreateDetaliuComanda", ReplyAction="http://tempuri.org/IAutoService/CreateDetaliuComandaResponse")]
    bool CreateDetaliuComanda(CarService.DetaliuComanda detaliuComanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/CreateDetaliuComanda", ReplyAction="http://tempuri.org/IAutoService/CreateDetaliuComandaResponse")]
    System.Threading.Tasks.Task<bool> CreateDetaliuComandaAsync(CarService.DetaliuComanda detaliuComanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/CreateImagine", ReplyAction="http://tempuri.org/IAutoService/CreateImagineResponse")]
    bool CreateImagine(CarService.Imagine imagine);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/CreateImagine", ReplyAction="http://tempuri.org/IAutoService/CreateImagineResponse")]
    System.Threading.Tasks.Task<bool> CreateImagineAsync(CarService.Imagine imagine);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/CreateOperatie", ReplyAction="http://tempuri.org/IAutoService/CreateOperatieResponse")]
    bool CreateOperatie(CarService.Operatie operatie);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/CreateOperatie", ReplyAction="http://tempuri.org/IAutoService/CreateOperatieResponse")]
    System.Threading.Tasks.Task<bool> CreateOperatieAsync(CarService.Operatie operatie);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/CreateMecanic", ReplyAction="http://tempuri.org/IAutoService/CreateMecanicResponse")]
    bool CreateMecanic(CarService.Mecanic mecanic);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/CreateMecanic", ReplyAction="http://tempuri.org/IAutoService/CreateMecanicResponse")]
    System.Threading.Tasks.Task<bool> CreateMecanicAsync(CarService.Mecanic mecanic);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/CreateComanda", ReplyAction="http://tempuri.org/IAutoService/CreateComandaResponse")]
    bool CreateComanda(CarService.Comanda comanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/CreateComanda", ReplyAction="http://tempuri.org/IAutoService/CreateComandaResponse")]
    System.Threading.Tasks.Task<bool> CreateComandaAsync(CarService.Comanda comanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/AddOperatie", ReplyAction="http://tempuri.org/IAutoService/AddOperatieResponse")]
    bool AddOperatie(CarService.Operatie operatieId, CarService.DetaliuComanda detaliuComanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/AddOperatie", ReplyAction="http://tempuri.org/IAutoService/AddOperatieResponse")]
    System.Threading.Tasks.Task<bool> AddOperatieAsync(CarService.Operatie operatieId, CarService.DetaliuComanda detaliuComanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/AddMecanics", ReplyAction="http://tempuri.org/IAutoService/AddMecanicsResponse")]
    bool AddMecanics(System.Collections.Generic.ICollection<CarService.Mecanic> selectedMecanics, CarService.DetaliuComanda detaliuComanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/AddMecanics", ReplyAction="http://tempuri.org/IAutoService/AddMecanicsResponse")]
    System.Threading.Tasks.Task<bool> AddMecanicsAsync(System.Collections.Generic.ICollection<CarService.Mecanic> selectedMecanics, CarService.DetaliuComanda detaliuComanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/UpdateClient", ReplyAction="http://tempuri.org/IAutoService/UpdateClientResponse")]
    bool UpdateClient(CarService.Client client);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/UpdateClient", ReplyAction="http://tempuri.org/IAutoService/UpdateClientResponse")]
    System.Threading.Tasks.Task<bool> UpdateClientAsync(CarService.Client client);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/UpdateDetaliuComanda", ReplyAction="http://tempuri.org/IAutoService/UpdateDetaliuComandaResponse")]
    bool UpdateDetaliuComanda(CarService.DetaliuComanda detaliuComanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/UpdateDetaliuComanda", ReplyAction="http://tempuri.org/IAutoService/UpdateDetaliuComandaResponse")]
    System.Threading.Tasks.Task<bool> UpdateDetaliuComandaAsync(CarService.DetaliuComanda detaliuComanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/UpdateMaterial", ReplyAction="http://tempuri.org/IAutoService/UpdateMaterialResponse")]
    bool UpdateMaterial(CarService.Material material);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/UpdateMaterial", ReplyAction="http://tempuri.org/IAutoService/UpdateMaterialResponse")]
    System.Threading.Tasks.Task<bool> UpdateMaterialAsync(CarService.Material material);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/DeleteMecanic", ReplyAction="http://tempuri.org/IAutoService/DeleteMecanicResponse")]
    bool DeleteMecanic(CarService.Mecanic mecanic);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/DeleteMecanic", ReplyAction="http://tempuri.org/IAutoService/DeleteMecanicResponse")]
    System.Threading.Tasks.Task<bool> DeleteMecanicAsync(CarService.Mecanic mecanic);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/DeleteOperatie", ReplyAction="http://tempuri.org/IAutoService/DeleteOperatieResponse")]
    bool DeleteOperatie(CarService.Operatie operatie);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/DeleteOperatie", ReplyAction="http://tempuri.org/IAutoService/DeleteOperatieResponse")]
    System.Threading.Tasks.Task<bool> DeleteOperatieAsync(CarService.Operatie operatie);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/DeleteMaterial", ReplyAction="http://tempuri.org/IAutoService/DeleteMaterialResponse")]
    bool DeleteMaterial(CarService.Material material);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/DeleteMaterial", ReplyAction="http://tempuri.org/IAutoService/DeleteMaterialResponse")]
    System.Threading.Tasks.Task<bool> DeleteMaterialAsync(CarService.Material material);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetClient", ReplyAction="http://tempuri.org/IAutoService/GetClientResponse")]
    CarService.Client GetClient(string searchClientString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetClient", ReplyAction="http://tempuri.org/IAutoService/GetClientResponse")]
    System.Threading.Tasks.Task<CarService.Client> GetClientAsync(string searchClientString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetClientAutos", ReplyAction="http://tempuri.org/IAutoService/GetClientAutosResponse")]
    System.Collections.Generic.ICollection<CarService.Auto> GetClientAutos(System.Guid Id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetClientAutos", ReplyAction="http://tempuri.org/IAutoService/GetClientAutosResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CarService.Auto>> GetClientAutosAsync(System.Guid Id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetAllDetaliuComandas", ReplyAction="http://tempuri.org/IAutoService/GetAllDetaliuComandasResponse")]
    System.Collections.Generic.ICollection<CarService.DetaliuComanda> GetAllDetaliuComandas();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetAllDetaliuComandas", ReplyAction="http://tempuri.org/IAutoService/GetAllDetaliuComandasResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CarService.DetaliuComanda>> GetAllDetaliuComandasAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetAllMaterials", ReplyAction="http://tempuri.org/IAutoService/GetAllMaterialsResponse")]
    System.Collections.Generic.ICollection<CarService.Material> GetAllMaterials();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetAllMaterials", ReplyAction="http://tempuri.org/IAutoService/GetAllMaterialsResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CarService.Material>> GetAllMaterialsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetAvailabelMecanics", ReplyAction="http://tempuri.org/IAutoService/GetAvailabelMecanicsResponse")]
    System.Collections.Generic.ICollection<CarService.Mecanic> GetAvailabelMecanics();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetAvailabelMecanics", ReplyAction="http://tempuri.org/IAutoService/GetAvailabelMecanicsResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CarService.Mecanic>> GetAvailabelMecanicsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetAvailabelMaterials", ReplyAction="http://tempuri.org/IAutoService/GetAvailabelMaterialsResponse")]
    System.Collections.Generic.ICollection<CarService.Material> GetAvailabelMaterials();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetAvailabelMaterials", ReplyAction="http://tempuri.org/IAutoService/GetAvailabelMaterialsResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CarService.Material>> GetAvailabelMaterialsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetAllMecanics", ReplyAction="http://tempuri.org/IAutoService/GetAllMecanicsResponse")]
    System.Collections.Generic.ICollection<CarService.Mecanic> GetAllMecanics();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetAllMecanics", ReplyAction="http://tempuri.org/IAutoService/GetAllMecanicsResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CarService.Mecanic>> GetAllMecanicsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetAllOrders", ReplyAction="http://tempuri.org/IAutoService/GetAllOrdersResponse")]
    System.Collections.Generic.ICollection<CarService.Comanda> GetAllOrders();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetAllOrders", ReplyAction="http://tempuri.org/IAutoService/GetAllOrdersResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CarService.Comanda>> GetAllOrdersAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetAllDoneOrders", ReplyAction="http://tempuri.org/IAutoService/GetAllDoneOrdersResponse")]
    System.Collections.Generic.ICollection<CarService.Comanda> GetAllDoneOrders();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetAllDoneOrders", ReplyAction="http://tempuri.org/IAutoService/GetAllDoneOrdersResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CarService.Comanda>> GetAllDoneOrdersAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetAllOperations", ReplyAction="http://tempuri.org/IAutoService/GetAllOperationsResponse")]
    System.Collections.Generic.ICollection<CarService.Operatie> GetAllOperations();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetAllOperations", ReplyAction="http://tempuri.org/IAutoService/GetAllOperationsResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CarService.Operatie>> GetAllOperationsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetOperationsTotalTime", ReplyAction="http://tempuri.org/IAutoService/GetOperationsTotalTimeResponse")]
    int GetOperationsTotalTime();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetOperationsTotalTime", ReplyAction="http://tempuri.org/IAutoService/GetOperationsTotalTimeResponse")]
    System.Threading.Tasks.Task<int> GetOperationsTotalTimeAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/CanBeRefuzata", ReplyAction="http://tempuri.org/IAutoService/CanBeRefuzataResponse")]
    bool CanBeRefuzata(System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/CanBeRefuzata", ReplyAction="http://tempuri.org/IAutoService/CanBeRefuzataResponse")]
    System.Threading.Tasks.Task<bool> CanBeRefuzataAsync(System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/SetComandaStatus", ReplyAction="http://tempuri.org/IAutoService/SetComandaStatusResponse")]
    bool SetComandaStatus(System.Guid id, CarService.StareComanda stareComanda, string descriere);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/SetComandaStatus", ReplyAction="http://tempuri.org/IAutoService/SetComandaStatusResponse")]
    System.Threading.Tasks.Task<bool> SetComandaStatusAsync(System.Guid id, CarService.StareComanda stareComanda, string descriere);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/ComandaAddMaterial", ReplyAction="http://tempuri.org/IAutoService/ComandaAddMaterialResponse")]
    bool ComandaAddMaterial(System.Guid materialId, System.Guid detaliuComandaId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/ComandaAddMaterial", ReplyAction="http://tempuri.org/IAutoService/ComandaAddMaterialResponse")]
    System.Threading.Tasks.Task<bool> ComandaAddMaterialAsync(System.Guid materialId, System.Guid detaliuComandaId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetProgramareClientsList", ReplyAction="http://tempuri.org/IAutoService/GetProgramareClientsListResponse")]
    System.Collections.Generic.ICollection<CarService.Client> GetProgramareClientsList(System.DateTime dataProgramare);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetProgramareClientsList", ReplyAction="http://tempuri.org/IAutoService/GetProgramareClientsListResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CarService.Client>> GetProgramareClientsListAsync(System.DateTime dataProgramare);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IAutoServiceChannel : IAutoService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AutoServiceClient : System.ServiceModel.ClientBase<IAutoService>, IAutoService
{
    
    public AutoServiceClient()
    {
    }
    
    public AutoServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AutoServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AutoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AutoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool CreateClient(CarService.Client client)
    {
        return base.Channel.CreateClient(client);
    }
    
    public System.Threading.Tasks.Task<bool> CreateClientAsync(CarService.Client client)
    {
        return base.Channel.CreateClientAsync(client);
    }
    
    public bool CreateAuto(CarService.Auto auto)
    {
        return base.Channel.CreateAuto(auto);
    }
    
    public System.Threading.Tasks.Task<bool> CreateAutoAsync(CarService.Auto auto)
    {
        return base.Channel.CreateAutoAsync(auto);
    }
    
    public bool CreateMaterial(CarService.Material material)
    {
        return base.Channel.CreateMaterial(material);
    }
    
    public System.Threading.Tasks.Task<bool> CreateMaterialAsync(CarService.Material material)
    {
        return base.Channel.CreateMaterialAsync(material);
    }
    
    public bool CreateDetaliuComanda(CarService.DetaliuComanda detaliuComanda)
    {
        return base.Channel.CreateDetaliuComanda(detaliuComanda);
    }
    
    public System.Threading.Tasks.Task<bool> CreateDetaliuComandaAsync(CarService.DetaliuComanda detaliuComanda)
    {
        return base.Channel.CreateDetaliuComandaAsync(detaliuComanda);
    }
    
    public bool CreateImagine(CarService.Imagine imagine)
    {
        return base.Channel.CreateImagine(imagine);
    }
    
    public System.Threading.Tasks.Task<bool> CreateImagineAsync(CarService.Imagine imagine)
    {
        return base.Channel.CreateImagineAsync(imagine);
    }
    
    public bool CreateOperatie(CarService.Operatie operatie)
    {
        return base.Channel.CreateOperatie(operatie);
    }
    
    public System.Threading.Tasks.Task<bool> CreateOperatieAsync(CarService.Operatie operatie)
    {
        return base.Channel.CreateOperatieAsync(operatie);
    }
    
    public bool CreateMecanic(CarService.Mecanic mecanic)
    {
        return base.Channel.CreateMecanic(mecanic);
    }
    
    public System.Threading.Tasks.Task<bool> CreateMecanicAsync(CarService.Mecanic mecanic)
    {
        return base.Channel.CreateMecanicAsync(mecanic);
    }
    
    public bool CreateComanda(CarService.Comanda comanda)
    {
        return base.Channel.CreateComanda(comanda);
    }
    
    public System.Threading.Tasks.Task<bool> CreateComandaAsync(CarService.Comanda comanda)
    {
        return base.Channel.CreateComandaAsync(comanda);
    }
    
    public bool AddOperatie(CarService.Operatie operatieId, CarService.DetaliuComanda detaliuComanda)
    {
        return base.Channel.AddOperatie(operatieId, detaliuComanda);
    }
    
    public System.Threading.Tasks.Task<bool> AddOperatieAsync(CarService.Operatie operatieId, CarService.DetaliuComanda detaliuComanda)
    {
        return base.Channel.AddOperatieAsync(operatieId, detaliuComanda);
    }
    
    public bool AddMecanics(System.Collections.Generic.ICollection<CarService.Mecanic> selectedMecanics, CarService.DetaliuComanda detaliuComanda)
    {
        return base.Channel.AddMecanics(selectedMecanics, detaliuComanda);
    }
    
    public System.Threading.Tasks.Task<bool> AddMecanicsAsync(System.Collections.Generic.ICollection<CarService.Mecanic> selectedMecanics, CarService.DetaliuComanda detaliuComanda)
    {
        return base.Channel.AddMecanicsAsync(selectedMecanics, detaliuComanda);
    }
    
    public bool UpdateClient(CarService.Client client)
    {
        return base.Channel.UpdateClient(client);
    }
    
    public System.Threading.Tasks.Task<bool> UpdateClientAsync(CarService.Client client)
    {
        return base.Channel.UpdateClientAsync(client);
    }
    
    public bool UpdateDetaliuComanda(CarService.DetaliuComanda detaliuComanda)
    {
        return base.Channel.UpdateDetaliuComanda(detaliuComanda);
    }
    
    public System.Threading.Tasks.Task<bool> UpdateDetaliuComandaAsync(CarService.DetaliuComanda detaliuComanda)
    {
        return base.Channel.UpdateDetaliuComandaAsync(detaliuComanda);
    }
    
    public bool UpdateMaterial(CarService.Material material)
    {
        return base.Channel.UpdateMaterial(material);
    }
    
    public System.Threading.Tasks.Task<bool> UpdateMaterialAsync(CarService.Material material)
    {
        return base.Channel.UpdateMaterialAsync(material);
    }
    
    public bool DeleteMecanic(CarService.Mecanic mecanic)
    {
        return base.Channel.DeleteMecanic(mecanic);
    }
    
    public System.Threading.Tasks.Task<bool> DeleteMecanicAsync(CarService.Mecanic mecanic)
    {
        return base.Channel.DeleteMecanicAsync(mecanic);
    }
    
    public bool DeleteOperatie(CarService.Operatie operatie)
    {
        return base.Channel.DeleteOperatie(operatie);
    }
    
    public System.Threading.Tasks.Task<bool> DeleteOperatieAsync(CarService.Operatie operatie)
    {
        return base.Channel.DeleteOperatieAsync(operatie);
    }
    
    public bool DeleteMaterial(CarService.Material material)
    {
        return base.Channel.DeleteMaterial(material);
    }
    
    public System.Threading.Tasks.Task<bool> DeleteMaterialAsync(CarService.Material material)
    {
        return base.Channel.DeleteMaterialAsync(material);
    }
    
    public CarService.Client GetClient(string searchClientString)
    {
        return base.Channel.GetClient(searchClientString);
    }
    
    public System.Threading.Tasks.Task<CarService.Client> GetClientAsync(string searchClientString)
    {
        return base.Channel.GetClientAsync(searchClientString);
    }
    
    public System.Collections.Generic.ICollection<CarService.Auto> GetClientAutos(System.Guid Id)
    {
        return base.Channel.GetClientAutos(Id);
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CarService.Auto>> GetClientAutosAsync(System.Guid Id)
    {
        return base.Channel.GetClientAutosAsync(Id);
    }
    
    public System.Collections.Generic.ICollection<CarService.DetaliuComanda> GetAllDetaliuComandas()
    {
        return base.Channel.GetAllDetaliuComandas();
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CarService.DetaliuComanda>> GetAllDetaliuComandasAsync()
    {
        return base.Channel.GetAllDetaliuComandasAsync();
    }
    
    public System.Collections.Generic.ICollection<CarService.Material> GetAllMaterials()
    {
        return base.Channel.GetAllMaterials();
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CarService.Material>> GetAllMaterialsAsync()
    {
        return base.Channel.GetAllMaterialsAsync();
    }
    
    public System.Collections.Generic.ICollection<CarService.Mecanic> GetAvailabelMecanics()
    {
        return base.Channel.GetAvailabelMecanics();
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CarService.Mecanic>> GetAvailabelMecanicsAsync()
    {
        return base.Channel.GetAvailabelMecanicsAsync();
    }
    
    public System.Collections.Generic.ICollection<CarService.Material> GetAvailabelMaterials()
    {
        return base.Channel.GetAvailabelMaterials();
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CarService.Material>> GetAvailabelMaterialsAsync()
    {
        return base.Channel.GetAvailabelMaterialsAsync();
    }
    
    public System.Collections.Generic.ICollection<CarService.Mecanic> GetAllMecanics()
    {
        return base.Channel.GetAllMecanics();
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CarService.Mecanic>> GetAllMecanicsAsync()
    {
        return base.Channel.GetAllMecanicsAsync();
    }
    
    public System.Collections.Generic.ICollection<CarService.Comanda> GetAllOrders()
    {
        return base.Channel.GetAllOrders();
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CarService.Comanda>> GetAllOrdersAsync()
    {
        return base.Channel.GetAllOrdersAsync();
    }
    
    public System.Collections.Generic.ICollection<CarService.Comanda> GetAllDoneOrders()
    {
        return base.Channel.GetAllDoneOrders();
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CarService.Comanda>> GetAllDoneOrdersAsync()
    {
        return base.Channel.GetAllDoneOrdersAsync();
    }
    
    public System.Collections.Generic.ICollection<CarService.Operatie> GetAllOperations()
    {
        return base.Channel.GetAllOperations();
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CarService.Operatie>> GetAllOperationsAsync()
    {
        return base.Channel.GetAllOperationsAsync();
    }
    
    public int GetOperationsTotalTime()
    {
        return base.Channel.GetOperationsTotalTime();
    }
    
    public System.Threading.Tasks.Task<int> GetOperationsTotalTimeAsync()
    {
        return base.Channel.GetOperationsTotalTimeAsync();
    }
    
    public bool CanBeRefuzata(System.Guid id)
    {
        return base.Channel.CanBeRefuzata(id);
    }
    
    public System.Threading.Tasks.Task<bool> CanBeRefuzataAsync(System.Guid id)
    {
        return base.Channel.CanBeRefuzataAsync(id);
    }
    
    public bool SetComandaStatus(System.Guid id, CarService.StareComanda stareComanda, string descriere)
    {
        return base.Channel.SetComandaStatus(id, stareComanda, descriere);
    }
    
    public System.Threading.Tasks.Task<bool> SetComandaStatusAsync(System.Guid id, CarService.StareComanda stareComanda, string descriere)
    {
        return base.Channel.SetComandaStatusAsync(id, stareComanda, descriere);
    }
    
    public bool ComandaAddMaterial(System.Guid materialId, System.Guid detaliuComandaId)
    {
        return base.Channel.ComandaAddMaterial(materialId, detaliuComandaId);
    }
    
    public System.Threading.Tasks.Task<bool> ComandaAddMaterialAsync(System.Guid materialId, System.Guid detaliuComandaId)
    {
        return base.Channel.ComandaAddMaterialAsync(materialId, detaliuComandaId);
    }
    
    public System.Collections.Generic.ICollection<CarService.Client> GetProgramareClientsList(System.DateTime dataProgramare)
    {
        return base.Channel.GetProgramareClientsList(dataProgramare);
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CarService.Client>> GetProgramareClientsListAsync(System.DateTime dataProgramare)
    {
        return base.Channel.GetProgramareClientsListAsync(dataProgramare);
    }
}
