//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace PostComment
{
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class Comment
    {
        public Comment()
        {
            CommentId = new Guid();
        }

        [DataMember]
        public System.Guid CommentId { get; set; }

        [DataMember]
        public string Text { get; set; }

        [DataMember]
        public System.Guid PostPostId { get; set; }

        [DataMember]
        public virtual Post Post { get; set; }
    }
}
