//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAutoLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {
        public System.Guid AutoId { get; set; }
        public string NumarAuto { get; set; }
        public string SerieSasiu { get; set; }
    }
}
